### ISSUE TITLE
compileErrors doesn't return all errors

### ISSUE THREAD

**Issue by robstoll** [scalameta/munit#750] opened 2024-03-05 17:52 UTC
Consider the following:
```
assertNoDiff(
   compileErrors("1.isInstanceOf[String]"),
  "cannot test if value of type Int is a reference of class String"
)
```

**Comment by erikerlandson** [comment] 2024-03-29 23:45
I am also seeing this, in coulomb. My compiler is `3.4.2-RC1-xxxxx-NIGHTLY`

```scala
// this is returning empty error list
val x = compileErrors("3.withUnit[Second] * 5d.withUnit[Kilogram]")
println(s"x= $x")
```

However if I try to compile, this errors out (as it should)
```scala
val x = 3.withUnit[Second] * 5d.withUnit[Kilogram]
```
```
[error] -- [E172] Type Error: /home/eje/git/coulomb/core/src/test/scala/coulomb/quantity.scala:232:58 
[error] 232 |        val x = 3.withUnit[Second] * 5d.withUnit[Kilogram]
[error]     |                                                          ^
[error]     |No given instance of type algebra.ring.MultiplicativeSemigroup[Double | Int] was found for parameter alg of method * in object Quantity
[error] one error found
```

**Comment by erikerlandson** [comment] 2024-03-30 14:55
This is a blocker for me. A lot of my unit tests are about verifying expressions that do *not* compile.

**Comment by erikerlandson** [comment] 2024-03-30 15:04
In my case this issue may be duplicate of #711

**Comment by tgodzik** [comment] 2024-04-16 10:22
> @tgodzik I am afraid I am not sure if I get what you mean. I guess you mean the underlying of compileErrors in the compiler is buggy right and that's way it is hard for munit to fix this. Correct?

Actually, we were missing transient keyword, which is suggested to be used in this specific case. You can try using this method:
```
transparent inline def compileErrorsFixed(inline code: String): String = {
    val errors = scala.compiletime.testing.typeCheckErrors(code)
    errors
      .map { error =>
        val indent = " " * (error.column - 1)
        val trimMessage = error.message.linesIterator
          .map { line =>
            if line.matches(" +") then ""
            else line
          }
          .mkString("\n")
        val separator = if error.message.contains('\n') then "\n" else " "
        s"error:$separator$trimMessage\n${error.lineContent}\n$indent^"
      }
      .mkString("\n")
  }
  ```
  explicitely to see if adding the keyword helps in your case

**Comment by tgodzik** [comment] 2024-04-16 15:35
Ok, let us know if anything pops up again. 

Coming back to the initial error in this issue it seems this is caused by a bug in the compiler or might actually be on purpose. Will ask.

**Comment by tgodzik** [comment] 2024-04-16 15:48
So it looks like this is an actual expected behaviour as the error in `1.isInstanceOf[String]` is produced in another phase. If needed please raise an issue in the compiler @robstoll

**Closed by tgodzik** 2024-04-16 15:48 UTC
