### ISSUE TITLE
Warning on Scala 3 when using a functional fixture

### ISSUE THREAD

**Issue by julienrf** [scalameta/munit#183] opened 2020-08-30 09:54 UTC
The code example given in [the documentation](https://scalameta.org/munit/docs/fixtures.html#functional-test-local-fixtures) leads to a warning when compiled with Scala 3:

~~~ text
[warn] 14 |  files.test("basic") { file =>
[warn]    |             ^^^^^^^
[warn]    |Use of implicit conversion method testOptionsFromString in trait TestOptionsConversions should be enabled
[warn]    |by adding the import clause 'import scala.language.implicitConversions'
[warn]    |or by setting the compiler option -language:implicitConversions.
[warn]    |See the Scala docs for value scala.language.implicitConversions for a discussion
[warn]    |why the feature should be explicitly enabled.
[warn] one warning found
~~~

I see several possible solutions, please let me know if you have a preference.

1. Add an overload to the [`test` method of `FunFixture`](https://github.com/scalameta/munit/blob/fdceafac292ff487e35b036b069f4ea1238ba5f9/munit/shared/src/main/scala/munit/FunFixtures.scala#L22):
   ~~~ scala
   def test(name: String)(body: T => Any)(implicit location: Location): Unit =
     test(new TestOptions(name, Set.empty, location))(body)
   ~~~

2. Add a constructor for `TestOptions` that takes just a test name as parameter:
   ~~~ scala
   class TestOptions(...) {
     def this(name: String, tags: Set[Tag] = Set.empty)(implicit location: Location) = this(name, tags, location)
   }
   // Or:
   object TestOptions {
     def apply(name: String, tags: Set[Tag] = Set.empty)(implicit location: Location): TestOptions =
       new TestOptions(name, tags, location)
   }
   ~~~

3. I must say that the benefits of using `FunFixtures` are not clear to me over an _ad-hoc_ solution such as:
   ~~~ scala
   class FunFixtureSuite extends munit.FunSuite {

     def withFile(name: String)(body: Path => Any): Unit = {
       val file = Files.createTempFile("tmp", name)
       body(file)
       Files.deleteIfExists(file)
     }

     test("basic") {
       withFile("basic") { file =>
         assert(Files.isRegularFile(file), s"Files.isRegularFile($file)")
       }
     }
   }
   ~~~
  Well, the only difference is that with the `FunFixture` you get access to the `TestOptions` of the underlying test. However, this could be achieved by adding another overload of the `test` method in `FunSuite`:
   ~~~ scala
   def test(name: String)(body: TestOptions => Any): Unit = ...
   ~~~
   Or, by providing a method `thisTest` in `FunSuite`, that would be set to the `TestOptions` of the currently running test.

**Comment by olafurpg** [comment] 2020-08-30 11:36
Thank you for reporting! This looks like a duplicate of https://github.com/scalameta/munit/issues/96

Has there been made a final decision on how implicit conversions will work in Dotty? The last I saw was here https://contributors.scala-lang.org/t/can-we-wean-scala-off-implicit-conversions/4388

The magnet pattern is used in a lot of widely used libraries and my understanding is that it will continue to work in Dotty.

**Comment by julienrf** [comment] 2020-08-30 13:41
Well, that one is a bit different than #96 but related, yes. The difference is that there is no workaround possible based on extension methods.

**Comment by olafurpg** [comment] 2020-08-31 06:14
I had forgotten we added a `FunSuite.test` overload to accept a string argument. I opened #184 adding a similar overload in `FunFixture` and also added new constructors for `TestOptions` so you can do `TestOptions("name")`.

The implicit conversion warnings are still reported when using extension methods like `test("hello".only)`. It would be nice to avoid those warnings as well but I'm not sure what's the best way to accomplish that in Dotty. Maybe we should copy-paste the `TestOptions` methods into an extension class 🤔

**Closed** 2020-08-31 06:30 UTC

**Comment by olafurpg** [comment] 2020-08-31 07:59
I took a stab at removing the warnings for usage like `test("hello".only)` by using dotty extension methods https://github.com/scalameta/munit/commit/b68804d621296ede7b77b6e7fea978684f80c493

The problem with this approach is that it won't help when users create helper methods to create tests
```scala
def check(name: TestOptions)(..): Unit = test(name) { ??? }

check("hello") { ... }
```

I would say >80% of my test suites are normally organized this way, although I suspect this pattern is less common in the wild.

Users could add a `check` overload for `name: String` but that feels unsatisfying, it's a big regression compared to writing only a single method.

>

**Comment by julienrf** [comment] 2020-08-31 12:04
I think it should be possible to have an extension method in Scala 3 and an implicit class in Scala 2, with separate source directories. However, I think that for binary compatibility reasons you’d still have to have the implicit class in the Scala 3 version?

**Comment by olafurpg** [comment] 2020-08-31 12:21
I opened https://github.com/scalameta/munit/issues/185 to follow up on this issue and complete the experiment in https://github.com/scalameta/munit/commit/b68804d621296ede7b77b6e7fea978684f80c493 That commit removes the need for implicit conversions in most common cases so it's a nice improvement over the current situation.

FYI I created a new MUnit v1.0 milestone to track the issues that are blocking the release https://github.com/scalameta/munit/milestone/1
