### ISSUE TITLE
Can't resolve junit-interfaces after latest build

### ISSUE THREAD

**Issue by gzoller** [scalameta/munit#60] opened 2020-02-18 17:28 UTC
When I do a compile/publishLocal, munit and junit-interfaces get 2 different generated SNAPSHOT versions.  For example my latest attempt:

munit: 0.5.2+3-cb874360+20200218-1135-SNAPSHOT
junit-interfaces: 0.5.2+3-cb874360+20200218-1136-SNAPSHOT

This means when I go to use munit I get a dependency failure on junit-interfaces.  (I'm pulling in the munit dependency in my project, and munit is pulling in junit-interfaces, but it's looking for the same version as munit.)

These 2 artifacts should have the same version, right?

**Comment by gzoller** [comment] 2020-02-18 19:03
Locally, this seemed to fix it for me, adding this to build.sbt in the junit section:

```
   crossScalaVersions := List(scala213, dotty),
```

**Comment by olafurpg** [comment] 2020-02-18 19:47
Do you have any diffs locally? You may need to commit changes before publishing locally. You may also need to run publish local for 2.13.1 together with Dotty. 

The JUnit interface module should only have one scala version in crossScalaVersions.

**Comment by olafurpg** [comment] 2020-02-22 13:01
Closing with working as intended.

**Closed by olafurpg** 2020-02-22 13:01 UTC

**Comment by gzoller** [comment] 2020-02-22 15:18
I'm unclear about the instructions.  I'm doing this:
```
sbt>  + publishLocal
```

Should I be doing something else?  If I do this, I get artifacts with 2 different version stamps, which won't import on my dotty projects.

**Comment by olafurpg** [comment] 2020-02-22 15:19
Did you got commit before running the command? The version number dynamically changes based on the git status.

**Comment by olafurpg** [comment] 2020-02-22 15:21
BTW what local changes do you need that are not available in the latest stable release?

**Comment by gzoller** [comment] 2020-02-22 15:42
Confirmed.  Yes, git commit unified the version numbers.  I do some work on dotty itself, so I track the nightly builds, or a self-built master, so I need to reflect that in munit for my tests.  

BTW, heads-up... there are recent changes in dotty nightly that will break your MacroCompat.scala when you're ready to move to latest 0.23 build.  Minor things.

Where you have:
```scala
  def locationImpl()(given qctx: QuoteContext): Expr[Location] = {
    import qctx.tasty.{_, given}

and

  def clueImpl[T:Type](value: Expr[T])(given qctx: QuoteContext): Expr[Clue[T]] = {
    import qctx.tasty.{_, given }
```
You'll need:
```scala
  def locationImpl()(implicit qctx: QuoteContext): Expr[Location] = {
    import qctx.tasty.{_, given _}

and

  def clueImpl[T:Type](value: Expr[T])(implicit qctx: QuoteContext): Expr[Clue[T]] = {
    import qctx.tasty.{_, given _}
```

**Comment by olafurpg** [comment] 2020-02-22 16:49
Good to know. Feel free to send a PR adding cross build support for nightly Dotty versions.
