### ISSUE TITLE
[Scala 3] no implicit argument of type munit.Location was found for parameter loc

### ISSUE THREAD

**Issue by bilal-fazlani** [scalameta/munit#269] opened 2020-11-29 14:50 UTC
I am converting an existing scala 2 project to scala 3. Scala version is 3.0.0-M2

![image](https://user-images.githubusercontent.com/3396271/100545072-01109a00-3280-11eb-9cde-3fc0b54de326.png)

I am getting some error while trying to compile with munit tests.

`no implicit argument of type munit.Location was found for parameter loc of method assertEquals in trait Assertions`

`no implicit argument of type munit.Location was found for parameter loc of method test in class FunFixture`

### CODE

```
class JwtVerifierTest extends FunSuite with Fixtures {

  private val fixture = FunFixture.map2(keycloak, actorSystem())

  private case class TestToken(
      preferred_username: String,
      scope: String,
      sub: String,
      iss: String
  )

  private given dec as Decoder[TestToken] = Decoder.from(TestToken.apply _)

  fixture.test("can verify token") {
    case (_, actorSystem) =>
      implicit val system: ActorSystem[SpawnProtocol.Command] = actorSystem
      val client = new OIDCClient(
        s"http://localhost:${settings.port}/auth/realms/master/.well-known/openid-configuration"
      )
      println(BearerToken.fromServer(settings.port, "admin", "admin"))
      val manager = new PublicKeyManager(client, 10.seconds)
      val verifier = new JwtVerifier(client, manager)
      val token = BearerToken.fromServer(settings.port, "admin", "admin")
      val decoded = Await
        .result(verifier.verifyAndDecode[TestToken](token.token), 5.seconds)
        .get
      assertEquals(decoded.preferred_username, "admin")
  }
}
```

**Comment by gabro** [comment] 2020-11-30 08:09
Thank you for reporting, it seems I can reproduce this in Scastie with this minimized example:

https://scastie.scala-lang.org/LvRCcoNKTLiqFpafSyrUAg

```scala
class Suite extends munit.FunSuite {
  test("t") {
    assertEquals(1, 1)
  }
}
```

I'll take a look

**Comment by gabro** [comment] 2020-11-30 08:20
Some preliminary observations:

- MUnit test suite includes cases where `Location` must be synthesized by the compiler and they work across all supported versions
- When invoking `munit.Location.generate` in Scastie we get

```
Scala 2 macro cannot be used in Dotty. See https://dotty.epfl.ch/docs/reference/dropped-features/macros.html
To turn this error into a warning, pass -Xignore-scala2-macros to the compiler
```

even though `generate` is also a Scala 3 def macro, so it should pick up that one instead.

- The problem appears also with M1 and MUnit 0.7.18 (i.e. before I split this `MacroCompat` classes further, so that should not be the root cause)

I'll dig deeper, but my educated guess right now is an issue with the published jar.

**Comment by bilal-fazlani** [comment] 2020-11-30 08:27
Thank you for taking this up

**Comment by gabro** [comment] 2020-11-30 08:43
Ok, I think I could use some help here from someone more familiar with how Dotty macros and Scala 2 macros interact. Here's a simple reproduction of this issue we're observing:

```scala
object Repro  {
  munit.Location.generate
  // Scala 2 macro cannot be used in Dotty. See https://dotty.epfl.ch/docs/reference/dropped-features/macros.html
  // To turn this error into a warning, pass -Xignore-scala2-macros to the compiler
}
```

https://scastie.scala-lang.org/k1Vv7BT6TGW6YUWZ3gxxpw

Now, `generate` is a macro that is comes from different sources depending on the Scala version.

In Scala 2 we have

```scala
trait LocationMacro {
  implicit def generate: Location = macro locationImpl
}
```

whereas in Scala 3 (or Dotty 0.x) we have

```scala
trait LocationMacro {
  inline implicit def generate: Location = ${ locationImpl() }
}
```

I've tried to decompile the published jar to check what's going on and this is what I see in `munit.internal.MacroCompat`

<details>
<summary>Decompiled source</summary>


```java
// 
// Decompiled by Procyon v0.5.36
// 

package munit.internal;

import java.lang.invoke.SerializedLambda;
import scala.MatchError;
import scala.runtime.BoxesRunTime;
import scala.quoted.Liftable;
import scala.quoted.Liftable$;
import scala.quoted.Expr$;
import scala.collection.immutable.Seq;
import scala.quoted.Type$;
import munit.Clue;
import scala.quoted.Type;
import scala.Function2;
import scala.quoted.runtime.QuoteUnpickler;
import munit.Location;
import scala.quoted.Expr;
import scala.quoted.Quotes;
import scala.runtime.ModuleSerializationProxy;
import java.io.Serializable;

public final class MacroCompat$ implements Serializable
{
    public static final MacroCompat$ MODULE$;
    
    private MacroCompat$() {
    }
    
    static {
        MODULE$ = new MacroCompat$();
    }
    
    private Object writeReplace() {
        return new ModuleSerializationProxy((Class)MacroCompat$.class);
    }
    
    public Expr<Location> locationImpl(final Quotes x$1) {
        final Object pos = x$1.reflect().Position().ofMacroExpansion();
        final String path = x$1.reflect().SourceFileMethods().jpath(x$1.reflect().PositionMethods().sourceFile(pos)).toString();
        final int startLine = x$1.reflect().PositionMethods().startLine(pos) + 1;
        return (Expr<Location>)((QuoteUnpickler)x$1).unpickleExpr((Serializable)"XKGrH5mBAL5GaMRc/gAA39h1UTGRAAHFAYRBU1RzAYY8aW5pdD4BhW11bml0AYhMb2NhdGlvbgKCgoMBhGphdmEBhGxhbmcCgoWGAYZTdHJpbmcCgoeIAYVzY2FsYQGDSW50AoKKiz+EgYSJjAGLTWFjcm9Db21wYXQXgY4BiGludGVybmFsAoKCkAGJUG9zaXRpb25zAcVtdW5pdC9zaGFyZWQvc3JjL21haW4vc2NhbGEtMy4wLjAtTTIvbXVuaXQvaW50ZXJuYWwvTWFjcm9Db21wYXQuc2NhbGGApZOjiJtwjVVvg3WDNoKTh/+FgHWINoeTh/+FgXWLNopvj3WPNpGSm4YDoAPPhJMB+H6Yr4TdgLeJjoCRgL+PlICRgA==", (Function2)null, this::locationImpl$$anonfun$adapted$1);
    }
    
    public <T> Expr<Clue<T>> clueImpl(final Expr<T> value, final Type<T> evidence$1, final Quotes x$2) {
        final String source = x$2.reflect().PositionMethods().sourceCode(x$2.reflect().TreeMethods().pos(x$2.reflect().Term().of((Expr)value)));
        final String valueType = Type$.MODULE$.show((Type)evidence$1, x$2);
        return (Expr<Clue<T>>)((QuoteUnpickler)x$2).unpickleExpr((Serializable)"XKGrH5mBAEjldacYTQAA64tAMHOOAAKbAYRBU1RzAYY8aW5pdD4BhW11bml0AYRDbHVlAoKCgwGEamF2YQGEbGFuZwKChYYBhlN0cmluZwKCh4gBhk9iamVjdAKCh4o/hoGE/4mLiQGHTm90aGluZwGFc2NhbGEBg0FueQGBVAGBJAGMZXZpZGVuY2UkMSRfCoORgZIBi1NwbGljZWRUeXBlAYZxdW90ZWQCgo6VAYdydW50aW1lAoKWlwKCmJQ/goGZAYtNYWNyb0NvbXBhdBeBmwGIaW50ZXJuYWwCgoKdAYlQb3NpdGlvbnMBxW11bml0L3NoYXJlZC9zcmMvbWFpbi9zY2FsYS0zLjAuMC1NMi9tdW5pdC9pbnRlcm5hbC9NYWNyb0NvbXBhdC5zY2FsYYDgk96M1oi3iZ5wjFVvg6qVoYh1gzaCrIKNgKOIdY02jnWPM52QNb2Th/+FgnWINoeThf+DgzOkk4X/g4Qzq4Obk6SK/4OAM5//g4Eznxeti3WUNpiIhXCaVTPPb5x1nDaen6eGBfsGsISgBdB+mKioe+i/hNOAAciXhZCAkYC/kYiAkYCviJSAkYA=", (Function2)this::clueImpl$$anonfun$adapted$1, this::clueImpl$$anonfun$adapted$2);
    }
    
    private final Expr locationImpl$$anonfun$1(final String path$1, final int startLine$1, final int x$0, final Seq x$1, final Quotes x$2) {
        Expr expr;
        if (0 == x$0) {
            expr = Expr$.MODULE$.apply((Object)path$1, (Liftable)Liftable$.MODULE$.StringLiftable(), x$2);
        }
        else {
            if (1 != x$0) {
                throw new MatchError((Object)BoxesRunTime.boxToInteger(x$0));
            }
            expr = Expr$.MODULE$.apply((Object)BoxesRunTime.boxToInteger(startLine$1), (Liftable)Liftable$.MODULE$.IntLiftable(), x$2);
        }
        return expr;
    }
    
    private final Expr locationImpl$$anonfun$adapted$1(final String path$2, final int startLine$2, final Object x$0, final Object x$1, final Object x$2) {
        return this.locationImpl$$anonfun$1(path$2, startLine$2, BoxesRunTime.unboxToInt(x$0), (Seq)x$1, (Quotes)x$2);
    }
    
    private final Type clueImpl$$anonfun$1(final Type evidence$1$1, final int x$0, final Seq x$1) {
        Type type;
        if (0 == x$0) {
            type = evidence$1$1;
        }
        else {
            if (1 != x$0) {
                throw new MatchError((Object)BoxesRunTime.boxToInteger(x$0));
            }
            type = evidence$1$1;
        }
        return type;
    }
    
    private final Type clueImpl$$anonfun$adapted$1(final Type evidence$1$2, final Object x$0, final Object x$1) {
        return this.clueImpl$$anonfun$1(evidence$1$2, BoxesRunTime.unboxToInt(x$0), (Seq)x$1);
    }
    
    private final Expr clueImpl$$anonfun$2(final Expr value$1, final String source$1, final String valueType$1, final int x$0, final Seq x$1, final Quotes x$2) {
        Expr expr = null;
        switch (x$0) {
            case 2: {
                expr = Expr$.MODULE$.apply((Object)source$1, (Liftable)Liftable$.MODULE$.StringLiftable(), x$2);
                break;
            }
            case 3: {
                expr = value$1;
                break;
            }
            case 4: {
                expr = Expr$.MODULE$.apply((Object)valueType$1, (Liftable)Liftable$.MODULE$.StringLiftable(), x$2);
                break;
            }
            default: {
                throw new MatchError((Object)BoxesRunTime.boxToInteger(x$0));
            }
        }
        return expr;
    }
    
    private final Expr clueImpl$$anonfun$adapted$2(final Expr value$2, final String source$2, final String valueType$2, final Object x$0, final Object x$1, final Object x$2) {
        return this.clueImpl$$anonfun$2(value$2, source$2, valueType$2, BoxesRunTime.unboxToInt(x$0), (Seq)x$1, (Quotes)x$2);
    }
}
```

</details>

which looks reasonable to me: I this is the Scala 3 version of `MacroCompat` which uses quotes, as expected.


I'm drawing a blank of what the problem may be, any ideas @olafurpg or anyone from the Dotty team? @bishabosha @smarter?

**Comment by gabro** [comment] 2020-11-30 08:44
Ahh, an idea: @bilal-fazlani are you using `withDottyCompat` in your build? I just noticed that Scastie uses it and that may explain the strange behavior

**Comment by bilal-fazlani** [comment] 2020-11-30 08:49
Yes
https://github.com/bilal-fazlani/akka-http-jwt-auth/blob/dotty/build.sbt#L52-L64

![image](https://user-images.githubusercontent.com/3396271/100587701-eccbac00-3316-11eb-8b54-001e9501e8dd.png)

**Comment by gabro** [comment] 2020-11-30 08:56
Ok, removing should fix the issue.

`withDottyCompat` is needed for modules that are not cross-published against Dotty/Scala 3 and it will pick up the _2.13 jar instead.

This works for modules which do not have Scala 2 macros (since they are forward compatible with Dotty), but it will break modules like MUnit that cross-compile to provide macro support across all Scala versions.

This explains why the compile "sees" the Scala 2 `generate` macro, instead of the Scala 3 one.

I'm fairly confident this is the problem, so I'll go ahead and close the issue. Let me know if that's not the case and we can reopen it.

**Closed by gabro** 2020-11-30 08:56 UTC
Labels: bug

**Comment by bilal-fazlani** [comment] 2020-11-30 09:03
Yes that worked. Thanks @gabro
